# -*- coding: utf-8 -*-
"""self_pruning_network_iniya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBUA8bP9weY2bYHAWnsuu9qTY_MJo8bz
"""

# Install required libraries
!pip install torch torchvision matplotlib tqdm

import os
os.makedirs("results", exist_ok=True)

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from torch.optim import Adam
from tqdm import tqdm

class GatedLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super(GatedLinear, self).__init__()

        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))

        #  FIX: same shape as weight
        self.gate_params = nn.Parameter(torch.randn(out_features, in_features) - 2)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_params)
        effective_weight = self.weight * gates
        return F.linear(x, effective_weight, self.bias)

class MyPruningNet(nn.Module):
    def __init__(self):
        super(MyPruningNet, self).__init__()

        self.flatten = nn.Flatten()

        # Different architecture (important difference)
        self.fc1 = GatedLinear(32*32*3, 256)
        self.fc2 = GatedLinear(256, 128)
        self.fc3 = GatedLinear(128, 10)

        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

def get_data():
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5,), (0.5,))
    ])

    train = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
    test = datasets.CIFAR10(root="./data", train=False, download=True, transform=transform)

    train_loader = DataLoader(train, batch_size=64, shuffle=True)
    test_loader = DataLoader(test, batch_size=64)

    return train_loader, test_loader

def sparsity_loss(model):
    loss = 0
    for m in model.modules():
        if isinstance(m, GatedLinear):
            gates = torch.sigmoid(m.gate_params)
            loss += torch.mean(gates)   # change here
    return loss

def train_model(model, train_loader, lambda_val):
    optimizer = Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    model.train()

    for epoch in range(8):  # keep 5 for faster run
        total_loss = 0

        for x, y in tqdm(train_loader):
            outputs = model(x)

            loss1 = criterion(outputs, y)
            loss2 = sparsity_loss(model)

            loss = loss1 + lambda_val * loss2

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss:.2f}")

def evaluate(model, test_loader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for x, y in test_loader:
            outputs = model(x)
            preds = torch.argmax(outputs, dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

    acc = 100 * correct / total
    print(f"Accuracy: {acc:.2f}%")
    return acc

def calculate_sparsity(model, threshold = 0.1):
    total = 0
    pruned = 0

    for m in model.modules():
        if isinstance(m, GatedLinear):
            gates = torch.sigmoid(m.gate_params)
            total += gates.numel()
            pruned += (gates < threshold).sum().item()

    sparsity = 100 * pruned / total
    print(f"Sparsity: {sparsity:.2f}%")
    return sparsity

train_loader, test_loader = get_data()

lambda_values = [0.0001, 0.001, 0.01]
results = []

for lam in lambda_values:
    print(f"\nTraining with lambda = {lam}")

    model = MyPruningNet()
    train_model(model, train_loader, lam)

    acc = evaluate(model, test_loader)
    sp = calculate_sparsity(model)

    results.append((lam, acc, sp))

print("\nFinal Results:")
for r in results:
    print(r)

import matplotlib.pyplot as plt

lambdas = [r[0] for r in results]
accuracies = [r[1] for r in results]
sparsities = [r[2] for r in results]

plt.figure()

plt.plot(lambdas, accuracies, marker='o', label='Accuracy')
plt.plot(lambdas, sparsities, marker='o', linestyle='--', label='Sparsity')

plt.xlabel("Lambda (λ)")
plt.ylabel("Percentage")
plt.title("Sparsity vs Accuracy Trade-Off")
plt.legend()

plt.savefig("results/sparsity_vs_accuracy.png")
plt.show()

def plot_gate_distribution(model):
    import numpy as np

    gates = []
    for m in model.modules():
        if isinstance(m, GatedLinear):
            g = torch.sigmoid(m.gate_params).detach().cpu().numpy().flatten()
            gates.append(g)

    gates = np.concatenate(gates)

    plt.hist(gates, bins=50)
    plt.title("Gate Value Distribution")
    plt.xlabel("Gate Values")
    plt.ylabel("Frequency")
    plt.savefig("results/gate_distribution.png")
    plt.show()

plot_gate_distribution(model)

